server:
  port: 8090
  session-timeout: 60

security.basic.enabled: false
endpoints.shutdown.enabled: true

spring.profiles.active: localdb
spring.profiles.include: security, mailon

---
spring:
  profiles: security

jwt:
  header: X-Auth-Token
  secret: mySecret
  expiration: 604800

---
spring:
  profiles: testdb
  datasource:
    url: jdbc:mariadb://server:3306/pmc-db
    username: pmc-db-user
    password: pass
  jpa.hibernate.ddl-auto: validate
server:
  port: 8080

---
spring:
  profiles: localdb
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  profiles: mailon

mail:
  host: smtp.gmail.com
  port: 587
  username: correo@gmail.com
  password: sadasd
  from.default: notificacion@pmc-servie.com
  to.default: notificacion@pmc-servie.com
  subject.default: Notificacion lupa
  transport.protocol: smtp
  debug: on
  smtp:
    auth: true
    starttls.enable: true